### ISSUE TITLE
Certificate Error

### ISSUE THREAD

**Issue by dxvv-software** [datkat21/PowerPoint-Discord-RPC#1]

**Comment by datkat21** [comment]
Could you please provide more details? I think this error is caused because the certificate I used for signing the release 1.0 is not meant for release which will be fixed at the time 1.1 releases

**Comment by datkat21** [comment]
I'm currently working on releasing a new version which should be working.

**Comment by dxvv-software** [comment]
didnt i tell you on discord?

**Comment by datkat21** [comment]
This issue _should_ be fixed once the next release is out in a bit.
